server:
  port:
    8888

spring:
  profiles:
    active:
      vault
  cloud:
    config:
      server:
        health:
          enabled:
            false
        vault:
          backend: secret/data
          order:
            1
        git:
          order:
            2
          uri:
            https://github.com/johnboyes/{application}-config
